services:
  backend:
    build: .
    container_name: taxguru-backend
    ports: 
      - 8080:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: taxguru-db
    ports: 
      - 8081:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taxguru"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    container_name: taxguru-frontend
    ports:
      - 4173:4173

volumes:
  db-data:
    