spring:
  datasource:
    url: ${PG_DB_URL}/taxguru
    username: ${PG_DB_USER}
    password: ${PG_DB_PW}

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      skillstorm: DEBUG